using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json;
using System.Text.Json.Serialization;
using Anthropic.Client.Core;
using Anthropic.Client.Exceptions;

namespace Anthropic.Client.Models.Messages;

[JsonConverter(typeof(ModelConverter<Message>))]
public sealed record class Message : ModelBase, IFromRaw<Message>
{
    /// <summary>
    /// Unique object identifier.
    ///
    /// The format and length of IDs may change over time.
    /// </summary>
    public required string ID
    {
        get
        {
            if (!this.Properties.TryGetValue("id", out JsonElement element))
                throw new AnthropicInvalidDataException(
                    "'id' cannot be null",
                    new ArgumentOutOfRangeException("id", "Missing required argument")
                );

            return JsonSerializer.Deserialize<string>(element, ModelBase.SerializerOptions)
                ?? throw new AnthropicInvalidDataException(
                    "'id' cannot be null",
                    new ArgumentNullException("id")
                );
        }
        set
        {
            this.Properties["id"] = JsonSerializer.SerializeToElement(
                value,
                ModelBase.SerializerOptions
            );
        }
    }

    /// <summary>
    /// Content generated by the model.
    ///
    /// This is an array of content blocks, each of which has a `type` that determines
    /// its shape.
    ///
    /// Example:
    ///
    /// ```json [{"type": "text", "text": "Hi, I'm Claude."}] ```
    ///
    /// If the request input `messages` ended with an `assistant` turn, then the response
    /// `content` will continue directly from that last turn. You can use this to
    /// constrain the model's output.
    ///
    /// For example, if the input `messages` were: ```json [   {"role": "user", "content":
    /// "What's the Greek name for Sun? (A) Sol (B) Helios (C) Sun"},   {"role":
    /// "assistant", "content": "The best answer is ("} ] ```
    ///
    /// Then the response `content` might be:
    ///
    /// ```json [{"type": "text", "text": "B)"}] ```
    /// </summary>
    public required List<ContentBlock> Content
    {
        get
        {
            if (!this.Properties.TryGetValue("content", out JsonElement element))
                throw new AnthropicInvalidDataException(
                    "'content' cannot be null",
                    new ArgumentOutOfRangeException("content", "Missing required argument")
                );

            return JsonSerializer.Deserialize<List<ContentBlock>>(
                    element,
                    ModelBase.SerializerOptions
                )
                ?? throw new AnthropicInvalidDataException(
                    "'content' cannot be null",
                    new ArgumentNullException("content")
                );
        }
        set
        {
            this.Properties["content"] = JsonSerializer.SerializeToElement(
                value,
                ModelBase.SerializerOptions
            );
        }
    }

    /// <summary>
    /// The model that will complete your prompt.\n\nSee [models](https://docs.anthropic.com/en/docs/models-overview)
    /// for additional details and options.
    /// </summary>
    public required ApiEnum<string, Model> Model
    {
        get
        {
            if (!this.Properties.TryGetValue("model", out JsonElement element))
                throw new AnthropicInvalidDataException(
                    "'model' cannot be null",
                    new ArgumentOutOfRangeException("model", "Missing required argument")
                );

            return JsonSerializer.Deserialize<ApiEnum<string, Model>>(
                element,
                ModelBase.SerializerOptions
            );
        }
        set
        {
            this.Properties["model"] = JsonSerializer.SerializeToElement(
                value,
                ModelBase.SerializerOptions
            );
        }
    }

    /// <summary>
    /// Conversational role of the generated message.
    ///
    /// This will always be `"assistant"`.
    /// </summary>
    public JsonElement Role
    {
        get
        {
            if (!this.Properties.TryGetValue("role", out JsonElement element))
                throw new AnthropicInvalidDataException(
                    "'role' cannot be null",
                    new ArgumentOutOfRangeException("role", "Missing required argument")
                );

            return JsonSerializer.Deserialize<JsonElement>(element, ModelBase.SerializerOptions);
        }
        set
        {
            this.Properties["role"] = JsonSerializer.SerializeToElement(
                value,
                ModelBase.SerializerOptions
            );
        }
    }

    /// <summary>
    /// The reason that we stopped.
    ///
    /// This may be one the following values: * `"end_turn"`: the model reached a
    /// natural stopping point * `"max_tokens"`: we exceeded the requested `max_tokens`
    /// or the model's maximum * `"stop_sequence"`: one of your provided custom `stop_sequences`
    /// was generated * `"tool_use"`: the model invoked one or more tools * `"pause_turn"`:
    /// we paused a long-running turn. You may provide the response back as-is in
    /// a subsequent request to let the model continue. * `"refusal"`: when streaming
    /// classifiers intervene to handle potential policy violations
    ///
    /// In non-streaming mode this value is always non-null. In streaming mode, it
    /// is null in the `message_start` event and non-null otherwise.
    /// </summary>
    public required ApiEnum<string, StopReason>? StopReason
    {
        get
        {
            if (!this.Properties.TryGetValue("stop_reason", out JsonElement element))
                return null;

            return JsonSerializer.Deserialize<ApiEnum<string, StopReason>?>(
                element,
                ModelBase.SerializerOptions
            );
        }
        set
        {
            this.Properties["stop_reason"] = JsonSerializer.SerializeToElement(
                value,
                ModelBase.SerializerOptions
            );
        }
    }

    /// <summary>
    /// Which custom stop sequence was generated, if any.
    ///
    /// This value will be a non-null string if one of your custom stop sequences
    /// was generated.
    /// </summary>
    public required string? StopSequence
    {
        get
        {
            if (!this.Properties.TryGetValue("stop_sequence", out JsonElement element))
                return null;

            return JsonSerializer.Deserialize<string?>(element, ModelBase.SerializerOptions);
        }
        set
        {
            this.Properties["stop_sequence"] = JsonSerializer.SerializeToElement(
                value,
                ModelBase.SerializerOptions
            );
        }
    }

    /// <summary>
    /// Object type.
    ///
    /// For Messages, this is always `"message"`.
    /// </summary>
    public JsonElement Type
    {
        get
        {
            if (!this.Properties.TryGetValue("type", out JsonElement element))
                throw new AnthropicInvalidDataException(
                    "'type' cannot be null",
                    new ArgumentOutOfRangeException("type", "Missing required argument")
                );

            return JsonSerializer.Deserialize<JsonElement>(element, ModelBase.SerializerOptions);
        }
        set
        {
            this.Properties["type"] = JsonSerializer.SerializeToElement(
                value,
                ModelBase.SerializerOptions
            );
        }
    }

    /// <summary>
    /// Billing and rate-limit usage.
    ///
    /// Anthropic's API bills and rate-limits by token counts, as tokens represent
    /// the underlying cost to our systems.
    ///
    /// Under the hood, the API transforms requests into a format suitable for the
    /// model. The model's output then goes through a parsing stage before becoming
    /// an API response. As a result, the token counts in `usage` will not match
    /// one-to-one with the exact visible content of an API request or response.
    ///
    /// For example, `output_tokens` will be non-zero, even for an empty string response
    /// from Claude.
    ///
    /// Total input tokens in a request is the summation of `input_tokens`, `cache_creation_input_tokens`,
    /// and `cache_read_input_tokens`.
    /// </summary>
    public required Usage Usage
    {
        get
        {
            if (!this.Properties.TryGetValue("usage", out JsonElement element))
                throw new AnthropicInvalidDataException(
                    "'usage' cannot be null",
                    new ArgumentOutOfRangeException("usage", "Missing required argument")
                );

            return JsonSerializer.Deserialize<Usage>(element, ModelBase.SerializerOptions)
                ?? throw new AnthropicInvalidDataException(
                    "'usage' cannot be null",
                    new ArgumentNullException("usage")
                );
        }
        set
        {
            this.Properties["usage"] = JsonSerializer.SerializeToElement(
                value,
                ModelBase.SerializerOptions
            );
        }
    }

    public override void Validate()
    {
        _ = this.ID;
        foreach (var item in this.Content)
        {
            item.Validate();
        }
        this.Model.Validate();
        this.StopReason?.Validate();
        _ = this.StopSequence;
        this.Usage.Validate();
    }

    public Message()
    {
        this.Role = new();
        this.Type = new();
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    Message(Dictionary<string, JsonElement> properties)
    {
        Properties = properties;
    }
#pragma warning restore CS8618

    public static Message FromRawUnchecked(Dictionary<string, JsonElement> properties)
    {
        return new(properties);
    }
}
